/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Response containing multiple logs.
type ArrayOfLogsResponse struct {
	Data *[]Log `json:"data"`
	Meta *ArrayOfLogsResponseMeta `json:"meta,omitempty"`
}
