/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Base entity.
type Entity struct {
	// Unix timestamp when this entity was created.
	CreatedAt int64 `json:"createdAt,omitempty"`
	Id int32 `json:"id"`
	// Unix timestamp when this entity was last updated.
	UpdatedAt int64 `json:"updatedAt,omitempty"`
}
