/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// API information
type ApiInformation struct {
	// Name of the API
	Name string `json:"name"`
	// Version of the API
	Version string `json:"version"`
}
