/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A label attached to something for the purpose of identification.
type Tag struct {
	// Unix timestamp when this entity was created.
	CreatedAt int32 `json:"createdAt,omitempty"`
	Id int32 `json:"id"`
	// The label value of the tag.
	Text string `json:"text"`
	// Unix timestamp when this entity was last updated.
	UpdatedAt int32 `json:"updatedAt,omitempty"`
}
