/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Describes an intervention or an event that happened.
type Run struct {
	EnvironmentId string `json:"environmentId,omitempty"`
	BytesReadOut int32 `json:"bytesReadOut,omitempty"`
	// Unix timestamp when this entity was created.
	CreatedAt int32 `json:"createdAt,omitempty"`
	Id int32 `json:"id,omitempty"`
	NDetectors int32 `json:"nDetectors,omitempty"`
	NEpns int32 `json:"nEpns,omitempty"`
	NFlps int32 `json:"nFlps,omitempty"`
	NSubtimeframes int32 `json:"nSubtimeframes,omitempty"`
	// Repository hash
	PdpConfigOption string `json:"pdpConfigOption,omitempty"`
	// Library file location of the pdp topology descrption.
	PdpTopologyDescriptionLibraryFile string `json:"pdpTopologyDescriptionLibraryFile,omitempty"`
	RunNumber int32 `json:"runNumber,omitempty"`
	RunQuality *RunQuality `json:"runQuality,omitempty"`
	RunType *RunType `json:"runType,omitempty"`
	TfbDdMode string `json:"tfbDdMode,omitempty"`
	TimeO2End int64 `json:"timeO2End,omitempty"`
	TimeO2Start int64 `json:"timeO2Start,omitempty"`
	TimeTrgEnd int64 `json:"timeTrgEnd,omitempty"`
	TimeTrgStart int64 `json:"timeTrgStart,omitempty"`
	// Boolean if the trigger is enabled.
	TrgEnabled bool `json:"trgEnabled,omitempty"`
	// Boolean if the global run trigger is enabled.
	TrgGlobalRunEnabled bool `json:"trgGlobalRunEnabled,omitempty"`
	DdFlp bool `json:"dd_flp,omitempty"`
	Dcs bool `json:"dcs,omitempty"`
	Epn bool `json:"epn,omitempty"`
	EpnTopology string `json:"epnTopology,omitempty"`
	Detectors *Detectors `json:"detectors,omitempty"`
	// Unix timestamp when this entity was last updated.
	UpdatedAt int32 `json:"updatedAt,omitempty"`
}
