/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// An object containing references to the source of the error.
type ErrorSource struct {
	// A pointer to the associated entity in the request document.
	Pointer string `json:"pointer,omitempty"`
}
