/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Specifies the creation time related filter requirements for a request.
type FilterLogsCreatedOptions struct {
	// The earliest allowed unix timestamp for the fetched data.
	From int32 `json:"from,omitempty"`
	// The latest allowed unix timestamp for the fetched data.
	To int32 `json:"to,omitempty"`
}
