/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// RunType : Specifies the type of run.
type RunType string

// List of RunType
const (
	PHYSICS_RunType RunType = "physics"
	COSMICS_RunType RunType = "cosmics"
	TECHNICAL_RunType RunType = "technical"
)
