/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Describes an update to an environment
type UpdateEnvironment struct {
	ToredownAt *time.Time `json:"toredownAt,omitempty"`
	Status string `json:"status,omitempty"`
	StatusMessage string `json:"statusMessage,omitempty"`
	Run int32 `json:"run,omitempty"`
}
