/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// Detectors : Adds one or multiple detectors to the run.
type Detectors string

// List of DETECTORS
const (
	CPV_Detectors Detectors = "CPV"
	EMC_Detectors Detectors = "EMC"
	FDD_Detectors Detectors = "FDD"
	FT0_Detectors Detectors = "FT0"
	FV0_Detectors Detectors = "FV0"
	HMP_Detectors Detectors = "HMP"
	ITS_Detectors Detectors = "ITS"
	MCH_Detectors Detectors = "MCH"
	MFT_Detectors Detectors = "MFT"
	MID_Detectors Detectors = "MID"
	PHS_Detectors Detectors = "PHS"
	TOF_Detectors Detectors = "TOF"
	TPC_Detectors Detectors = "TPC"
	TRD_Detectors Detectors = "TRD"
	TST_Detectors Detectors = "TST"
	ZDC_Detectors Detectors = "ZDC"
)
