/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// The Environment object.
type Environment struct {
	Id string `json:"id"`
	// Unix timestamp when this entity was created.
	CreatedAt int32 `json:"createdAt,omitempty"`
	// Unix timestamp when this entity was last updated.
	UpdatedAt int32 `json:"updatedAt,omitempty"`
	// Unix timestamp when this entity was tore down.
	ToredownAt time.Time `json:"toredownAt,omitempty"`
	// The status of the environment.
	Status string `json:"status,omitempty"`
	// A message explaining the status or the current state of the environment.
	StatusMessage string `json:"statusMessage,omitempty"`
	// Array of minified Run objects.
	Runs []Run `json:"runs,omitempty"`
}
