/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Specifies the pagination requirements of a request.
type PaginationOptions struct {
	Limit int32 `json:"limit,omitempty"`
	Offset int64 `json:"offset,omitempty"`
}
