/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Response containing multiple runs.
type ArrayOfRunsResponse struct {
	Data *[]Run `json:"data"`
	Meta *ArrayOfRunsResponseMeta `json:"meta,omitempty"`
}
