/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Describes metadata of an attachment.
type Attachment struct {
	// Unix timestamp when this entity was created.
	CreatedAt int64 `json:"createdAt,omitempty"`
	Encoding string `json:"encoding,omitempty"`
	FileName string `json:"fileName,omitempty"`
	Id int32 `json:"id"`
	LogId int32 `json:"logId,omitempty"`
	MimeType string `json:"mimeType,omitempty"`
	OriginalName string `json:"originalName,omitempty"`
	Path string `json:"path,omitempty"`
	Size int64 `json:"size,omitempty"`
	// Unix timestamp when this entity was created.
	UpdatedAt int64 `json:"updatedAt,omitempty"`
}
