/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Response containing multiple environments.
type ArrayOfEnvironmentsResponse struct {
	Data *[]Environment `json:"data"`
	Meta *ArrayOfEnvironmentsResponseMeta `json:"meta,omitempty"`
}
