/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The metadata related to pagination.
type PaginationMeta struct {
	// The total number of pages which contain data.
	PageCount int64 `json:"pageCount"`
	// The total number of elements in the collection
	TotalCount int64 `json:"totalCount"`
}
