/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Describes an intervention or an event that happened.
type Run struct {
	ActivityId string `json:"activityId,omitempty"`
	BytesReadOut int64 `json:"bytesReadOut,omitempty"`
	// Unix timestamp when this entity was created.
	CreatedAt int64 `json:"createdAt,omitempty"`
	Id int32 `json:"id,omitempty"`
	NDetectors int64 `json:"nDetectors,omitempty"`
	NEpns int64 `json:"nEpns,omitempty"`
	NFlps int64 `json:"nFlps,omitempty"`
	NSubtimeframes int64 `json:"nSubtimeframes,omitempty"`
	RunNumber int64 `json:"runNumber,omitempty"`
	RunQuality *RunQuality `json:"runQuality,omitempty"`
	RunType *RunType `json:"runType,omitempty"`
	TimeO2End int64 `json:"timeO2End,omitempty"`
	TimeO2Start int64 `json:"timeO2Start,omitempty"`
	TimeTrgEnd int64 `json:"timeTrgEnd,omitempty"`
	TimeTrgStart int64 `json:"timeTrgStart,omitempty"`
	// Unix timestamp when this entity was last updated.
	UpdatedAt int64 `json:"updatedAt,omitempty"`
}
