/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// An Error object.
type ModelError struct {
	// A human-readable explanation specific to this occurrence of the problem.
	Detail string `json:"detail,omitempty"`
	Source *ErrorSource `json:"source,omitempty"`
	// The HTTP status code applicable to this problem.
	Status string `json:"status"`
	// A short, human-readable summary of the problem.
	Title string `json:"title"`
}
