/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Specifies the tag related filter requirements for a request.
type FilterLogsTagOptions struct {
	// The operation indicating the relation between the data.
	Operation string `json:"operation"`
	Values string `json:"values"`
}
