version: "3.7"

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
      target: production
    volumes:
      # Mounts the 'scripts' folder inside the host on '/opt'
      - './scripts:/opt'
    ports:
      # Expose the HTTP port to the host
      - 80:80
      # Expose the HTTPS port to the host
      - 443:443
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    depends_on: 
      - backend
