version: '3.7'

services:
  test_app:
    image: test-parallel-application:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TEST_TYPE: ${TEST_TYPE}
      NODE_ENV: test
      DATABASE_LOGGING: "False"
      JWT_SECRET: BOOKKEEPING-TEST-SUITE
      PAGE_ITEMS_LIMIT: 100
      DATABASE_HOST: test_db
      ALI_ECS_GUI_URL: "${ALI_ECS_GUI_URL:-http://localhost:8080}"
      FLP_INFOLOGGER_URL: "${FLP_INFOLOGGER_URL:-http://localhost:8081}"
      QC_GUI_URL: "${QC_GUI_URL:-http://localhost:8082}"
      ALI_FLP_INDEX_URL: "${ALI_FLP_INDEX_URL:-http://localhost:80}"
    links:
      - test_db
    restart: "no"
    depends_on:
      - test_db
    volumes:
      - type: bind
        read_only: true
        source: ./scripts
        target: /opt
      - type: bind
        source: ./database/storage
        target: /var/storage
        read_only: false

  test_db:
    image: mariadb:10.5.9
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-root}"
    restart: unless-stopped
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/mysql
      - type: bind
        read_only: true
        source: ./database/configuration
        target: /etc/mysql/conf.d
      - type: bind
        read_only: true
        source: ./database/populate
        target: /docker-entrypoint-initdb.d

volumes:
  database-data:
