version: "3.7"

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - "./scripts:/opt"
    links:
      - database
    ports:
      - "80:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=database

  database:
    image: mariadb:10.5.2
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--lower-case-table-names=2']
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: bookkeeping
      MYSQL_USER: cern
      MYSQL_PASSWORD: cern
