version: "3.7"

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      NODE_ENV: production
      DATABASE_HOST: database
    links:
      - database
    ports:
      - "80:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=database
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - OIDC_SECRET=${OIDC_SECRET}
      - OIDC_ID=${OIDC_ID}
      - OIDC_REDIRECT=${OIDC_REDIRECT}
    restart: unless-stopped
    volumes:
      - type: bind
        read_only: true
        source: ./scripts
        target: /opt

  database:
    image: mariadb:10.5.3
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    restart: unless-stopped
    volumes:
      - type: bind
        read_only: false
        source: ./database/data
        target: /var/lib/mysql
      - type: bind
        read_only: true
        source: ./database/configuration
        target: /etc/mysql/conf.d
      - type: bind
        read_only: true
        source: ./database/populate
        target: /docker-entrypoint-initdb.d
