version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    depends_on: 
      - backend
