version: "3.7"

services:
  application:
    build:
      target: test
    environment:
      NODE_ENV: test
    restart: "no"
    volumes:
      - type: bind
        read_only: false
        source: .
        target: /usr/src/app
      - type: volume
        target: /usr/src/app/node_modules

  database:
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-root}"
    restart: "no"
