version: "3.7"

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - "./scripts:/opt"
    links:
      - database
    ports:
      - "80:4000"

  database:
    image: mariadb:10.5.2
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: bookkeeping
      MYSQL_USER: cern
      MYSQL_PASSWORD: cern
