version: "3.7"

services:
  application:
    build:
      target: development
    environment:
      NODE_ENV: development
      DATABASE_LOGGING: "${DATABASE_LOGGING-True}"
      JWT_SECRET: BOOKKEEPING-DEV
      PUBLIC_DIRECTORIES_CONF: '/usr/src/app/public/dist;/usr/src/app/public/assets:assets'
    ports:
      - "4000:4000"
      - "4001:4001"
    restart: "no"
    volumes:
      - type: bind
        read_only: true
        source: ./packages/bookkeeping-server/lib
        target: /usr/src/app/lib
      - type: bind
        read_only: true
        source: ./packages/bookkeeping-server/proto
        target: /usr/src/app/proto
      - type: bind
        read_only: true
        source: ./packages/bookkeeping-webapp/lib
        target: /usr/src/app/public

  database:
    environment:
      MYSQL_ROOT_PASSWORD: cern
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        read_only: false
        source: database-data
        target: /var/lib/mysql

volumes:
  database-data: