version: "3.7"

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - "./scripts:/opt"
    links:
      - database
    ports:
      - "80:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=database

  database:
    image: mariadb:10.5.2
    restart: always
    volumes: 
      # Mounts the data directory as /var/lib/mysql inside the container, where the data files are written
      - "./database/data:/var/lib/mysql"
      # Mounts the configuration directory as /etc/mysql/conf.d inside the container, where custom configurations reside
      - "./database/configuration:/etc/mysql/conf.d"
      # Mounts the populate directory as /docker-entrypoint-initdb.d" inside the container, where population dumps reside
      - "./database/populate:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
