version: "3.8"

services:
  application:
    build:
      target: test
    environment:
      NODE_ENV: test
      JWT_SECRET: BOOKKEEPING-TEST-SUITE
    restart: "no"

  database:
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-root}"
    restart: "no"
