version: "3.7"

services:
  application:
    build:
      target: test
    environment:
      NODE_ENV: test
      JWT_SECRET: BOOKKEEPING-TEST-SUITE
    restart: "no"
    volumes:
      - type: bind
        read_only: false
        source: ./coverage
        target: /usr/src/app/coverage
      - type: bind
        read_only: true
        source: ./lib
        target: /usr/src/app/lib
      - type: bind
        read_only: true
        source: ./spec
        target: /usr/src/app/spec
      - type: bind
        read_only: true
        source: ./test
        target: /usr/src/app/test
      - type: bind
        read_only: true
        source: ./test
        target: /usr/src/app/test
      - type: bind
        read_only: true
        source: ./.nycrc
        target: /usr/src/app/.nycrc

  database:
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-root}"
    restart: "no"
