/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.0.0-beta2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AttachmentApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_AttachmentApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_AttachmentApi_H_


#include "../ApiClient.h"

#include "ArrayOfAttachmentsResponse.h"
#include "CreateAttachments.h"
#include "Errors.h"


#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  AttachmentApi 
{
public:

    explicit AttachmentApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~AttachmentApi();

    /// <summary>
    /// Create a new attachment on a log
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="createAttachments"></param>
    pplx::task<std::shared_ptr<ArrayOfAttachmentsResponse>> createAttachment(
        std::shared_ptr<CreateAttachments> createAttachments
    ) const;
    /// <summary>
    /// Get one specific attachment
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="attachmentId">The id of the attached to retrieve</param>
    pplx::task<std::shared_ptr<ArrayOfAttachmentsResponse>> getAttachment(
        int32_t attachmentId
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_AttachmentApi_H_ */

