/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.0.0-beta2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * LogApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_LogApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_LogApi_H_


#include "../ApiClient.h"

#include "ArrayOfAttachmentsResponse.h"
#include "ArrayOfLogsResponse.h"
#include "ArrayOfTagsResponse.h"
#include "AttachmentResponse.h"
#include "CreateLog.h"
#include "Errors.h"
#include "LogResponse.h"
#include "LogTreeResponse.h"


#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  LogApi 
{
public:

    explicit LogApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~LogApi();

    /// <summary>
    /// Adds a new log
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="createLog"></param>
    pplx::task<std::shared_ptr<LogResponse>> createLog(
        std::shared_ptr<CreateLog> createLog
    ) const;
    /// <summary>
    /// Get one specific attachment associated with a log
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="logId">The id of the log to retrieve</param>
    /// <param name="attachmentId">The id of the attached to retrieve</param>
    pplx::task<std::shared_ptr<AttachmentResponse>> getLogAttachment(
        int32_t logId,
        int32_t attachmentId
    ) const;
    /// <summary>
    /// Gets a log by Id
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="logId">The id of the log to retrieve</param>
    pplx::task<std::shared_ptr<LogResponse>> getLogById(
        int32_t logId
    ) const;
    /// <summary>
    /// Get the Log tree for a given Log
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="logId">The id of the log to retrieve</param>
    pplx::task<std::shared_ptr<LogTreeResponse>> getLogTree(
        int32_t logId
    ) const;
    /// <summary>
    /// Get all attachments associated with a log
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="logId">The id of the log to retrieve</param>
    pplx::task<std::shared_ptr<ArrayOfAttachmentsResponse>> listLogAttachments(
        int32_t logId
    ) const;
    /// <summary>
    /// List all logs
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    pplx::task<std::shared_ptr<ArrayOfLogsResponse>> listLogs(
    ) const;
    /// <summary>
    /// Lists all tags associated with a log
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="logId">The id of the log to retrieve</param>
    pplx::task<std::shared_ptr<ArrayOfTagsResponse>> listTagsByLogId(
        int32_t logId
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_LogApi_H_ */

