openapi: 3.0.0

info:
  title: ALICE Bookkeeping
  version: 0.0.0

servers:
  - url: '/api'

paths:
  /:
    get:
      responses:
        '200':
          description: API information
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  version:
                    type: string
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /logs:
    post:
      responses:
        '201':
          $ref: '#/components/responses/Created'
        '400':
          $ref: '#/components/responses/BadRequest'

components:
  schemas:
    DataResponse:
      type: object
      properties:
        data:
          type: array
      required:
        - data
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
      required:
        - errors
    Error:
      type: object
      properties:
        status:
          type: string
        title:
          type: string
        detail:
          type: string
      required:
        - status
        - title
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Created:
      description: Created
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DataResponse'
    ServiceUnavailable:
      description: Service Unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
