openapi: 3.0.0

info:
  title: ALICE Electronic Logbook
  version: 0.0.0

servers:
  - url: 'http://localhost:4000/api'

paths:
  /:
    get:
      responses:
        '200':
          description: API information
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  version:
                    type: string
