openapi: 3.0.0

info:
  title: ALICE Bookkeeping
  version: 0.0.0

servers:
  - url: '/api'

paths:
  /:
    get:
      operationId: getServerInformation
      summary: Get server information
      responses:
        '200':
          description: API information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiInformation'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /logs:
    post:
      operationId: createLog
      summary: Adds a new log
      responses:
        '201':
          $ref: '#/components/responses/Created'
        '400':
          $ref: '#/components/responses/BadRequest'
  /logs/{id}:
    parameters:
      - name: id
        in: path
        description: The id of the log to retrieve
        required: true
        schema:
          type: integer
          format: int64
    get:
      operationId: getLogById
      summary: Gets a log by Id
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/BadRequest'
  /status:
    get:
      operationId: getDeployInformation
      summary: Get deploy information
      responses:
        '200':
          description: Deploy information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeployInformation'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'

components:
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Created:
      description: Created
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DataResponse'
    OK:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DataResponse'
    ServiceUnavailable:
      description: Service Unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    ApiInformation:
      type: object
      properties:
        name:
          type: string
        version:
          type: string
      required:
        - name
        - version
    DataResponse:
      type: object
      properties:
        data:
          oneOf:
            - type: array
              items:
                type: object
            - type: object
      required:
        - data
    DeployInformation:
      type: object
      properties:
        age:
          type: number
        start:
          type: number
      required:
        - age
        - start
    Error:
      type: object
      properties:
        status:
          type: string
        title:
          type: string
        detail:
          type: string
      required:
        - status
        - title
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
      required:
        - errors
