/**
 * @license
 * Copyright CERN and copyright holders of ALICE O2. This software is
 * distributed under the terms of the GNU General Public License v3 (GPL
 * Version 3), copied verbatim in the file "COPYING".
 *
 * See http://alice-o2.web.cern.ch/license for full licensing information.
 *
 * In applying this license CERN does not waive the privileges and immunities
 * granted to it by virtue of its status as an Intergovernmental Organization
 * or submit itself to any jurisdiction.
 */

module.exports = {
    up: (queryInterface, _Sequelize) => queryInterface.bulkInsert('flp_roles', [
        {
            id: 1,
            name: 'FLP-TPC-1',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 40,
            bytes_fair_m_q_read_out: 60,
        },
        {
            id: 2,
            name: 'FLP-TPC-2',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 56,
            bytes_recording_read_out: 80,
            bytes_fair_m_q_read_out: 30,
        },
        {
            id: 3,
            name: 'FLP-TPC-3',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 76,
            bytes_recording_read_out: 50,
            bytes_fair_m_q_read_out: 20,
        },
        {
            id: 4,
            name: 'FLP-TPC-4',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 96,
            bytes_recording_read_out: 10,
            bytes_fair_m_q_read_out: 90,
        },
        {
            id: 5,
            name: 'FLP-TPC-5',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },

        {
            id: 6,
            name: 'FLP-TPC-6',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 7,
            name: 'FLP-TPC-7',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 8,
            name: 'FLP-TPC-8',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 9,
            name: 'FLP-TPC-9',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 10,
            name: 'FLP-TPC-10',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 11,
            name: 'FLP-TPC-11',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 12,
            name: 'FLP-TPC-12',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 13,
            name: 'FLP-TPC-13',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 14,
            name: 'FLP-TPC-14',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 15,
            name: 'FLP-TPC-15',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 16,
            name: 'FLP-TPC-16',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 17,
            name: 'FLP-TPC-17',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 18,
            name: 'FLP-TPC-18',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 19,
            name: 'FLP-TPC-19',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 20,
            name: 'FLP-TPC-20',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 21,
            name: 'FLP-TPC-21',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 22,
            name: 'FLP-TPC-22',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 23,
            name: 'FLP-TPC-23',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 24,
            name: 'FLP-TPC-24',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 25,
            name: 'FLP-TPC-25',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 26,
            name: 'FLP-TPC-26',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 27,
            name: 'FLP-TPC-27',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 28,
            name: 'FLP-TPC-28',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 29,
            name: 'FLP-TPC-29',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 30,
            name: 'FLP-TPC-30',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 31,
            name: 'FLP-TPC-31',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 32,
            name: 'FLP-TPC-32',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 33,
            name: 'FLP-TPC-33',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 34,
            name: 'FLP-TPC-34',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 35,
            name: 'FLP-TPC-35',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 36,
            name: 'FLP-TPC-36',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 37,
            name: 'FLP-TPC-37',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 38,
            name: 'FLP-TPC-38',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 39,
            name: 'FLP-TPC-39',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 40,
            name: 'FLP-TPC-40',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 41,
            name: 'FLP-TPC-41',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 42,
            name: 'FLP-TPC-42',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 43,
            name: 'FLP-TPC-43',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 44,
            name: 'FLP-TPC-44',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 45,
            name: 'FLP-TPC-45',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 46,
            name: 'FLP-TPC-46',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 47,
            name: 'FLP-TPC-47',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 48,
            name: 'FLP-TPC-48',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 49,
            name: 'FLP-TPC-49',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 50,
            name: 'FLP-TPC-50',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 51,
            name: 'FLP-TPC-51',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 52,
            name: 'FLP-TPC-52',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 53,
            name: 'FLP-TPC-53',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 54,
            name: 'FLP-TPC-54',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 55,
            name: 'FLP-TPC-55',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 56,
            name: 'FLP-TPC-56',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 57,
            name: 'FLP-TPC-57',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 58,
            name: 'FLP-TPC-58',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 59,
            name: 'FLP-TPC-59',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 60,
            name: 'FLP-TPC-60',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 61,
            name: 'FLP-TPC-61',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 62,
            name: 'FLP-TPC-62',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 63,
            name: 'FLP-TPC-63',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 64,
            name: 'FLP-TPC-64',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 65,
            name: 'FLP-TPC-65',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 66,
            name: 'FLP-TPC-66',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 67,
            name: 'FLP-TPC-67',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 68,
            name: 'FLP-TPC-68',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 69,
            name: 'FLP-TPC-69',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 70,
            name: 'FLP-TPC-70',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 71,
            name: 'FLP-TPC-71',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 72,
            name: 'FLP-TPC-72',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 73,
            name: 'FLP-TPC-73',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 74,
            name: 'FLP-TPC-74',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 75,
            name: 'FLP-TPC-75',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 76,
            name: 'FLP-TPC-76',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 77,
            name: 'FLP-TPC-77',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 78,
            name: 'FLP-TPC-78',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 79,
            name: 'FLP-TPC-79',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 80,
            name: 'FLP-TPC-80',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 81,
            name: 'FLP-TPC-81',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 82,
            name: 'FLP-TPC-82',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 83,
            name: 'FLP-TPC-83',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 84,
            name: 'FLP-TPC-84',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 85,
            name: 'FLP-TPC-85',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 86,
            name: 'FLP-TPC-86',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 87,
            name: 'FLP-TPC-87',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 88,
            name: 'FLP-TPC-88',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 89,
            name: 'FLP-TPC-89',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 90,
            name: 'FLP-TPC-90',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 91,
            name: 'FLP-TPC-91',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 92,
            name: 'FLP-TPC-92',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 93,
            name: 'FLP-TPC-93',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 94,
            name: 'FLP-TPC-94',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 95,
            name: 'FLP-TPC-95',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 96,
            name: 'FLP-TPC-96',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 97,
            name: 'FLP-TPC-97',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 98,
            name: 'FLP-TPC-98',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 99,
            name: 'FLP-TPC-99',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 100,
            name: 'FLP-TPC-100',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 101,
            name: 'FLP-TPC-101',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 102,
            name: 'FLP-TPC-102',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 103,
            name: 'FLP-TPC-103',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 104,
            name: 'FLP-TPC-104',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 32,
            bytes_recording_read_out: 90,
            bytes_fair_m_q_read_out: 15,
        },
        {
            id: 105,
            name: 'FLP-TPC-105',
            hostname: 'someserver.cern.ch',
            n_timeframes: 50,
            bytes_processed: 1024,
            bytes_equipment_read_out: 16,
            bytes_recording_read_out: 128,
            bytes_fair_m_q_read_out: 15,
        },

    ]),

    down: (queryInterface, _Sequelize) => queryInterface.bulkDelete('flp_roles', null, {}),
};
