/**
 * @license
 * Copyright CERN and copyright holders of ALICE O2. This software is
 * distributed under the terms of the GNU General Public License v3 (GPL
 * Version 3), copied verbatim in the file "COPYING".
 *
 * See http://alice-o2.web.cern.ch/license for full licensing information.
 *
 * In applying this license CERN does not waive the privileges and immunities
 * granted to it by virtue of its status as an Intergovernmental Organization
 * or submit itself to any jurisdiction.
 */

module.exports = {
    up: async (queryInterface) =>
        queryInterface.sequelize.transaction((transaction) =>
            Promise.all([
                queryInterface.bulkInsert('logs', [
                    {
                        id: 1,
                        title: 'First entry',
                        subtype: 'run',
                        origin: 'human',
                        user_id: 1,
                        text: 'Power interruption due to unplugged wire.',
                        created_at: new Date('2000-01-02 12:00:00 PM'),
                    },
                    {
                        id: 2,
                        title: 'Second entry',
                        subtype: 'comment',
                        origin: 'process',
                        user_id: 1,
                        text: 'Detected particle ABC123',
                        parent_log_id: 1,
                        root_log_id: 1,
                        created_at: new Date('2020-02-02 12:00:00 PM'),
                    },
                    {
                        id: 3,
                        title: 'Third entry',
                        subtype: 'announcement',
                        origin: 'human',
                        text: 'Cake at the particle accelerator!',
                        parent_log_id: 1,
                        root_log_id: 1,
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 4,
                        title: 'Fourth entry',
                        subtype: 'comment',
                        origin: 'human',
                        user_id: 2,
                        text: 'The cake is a lie!',
                        parent_log_id: 2,
                        root_log_id: 1,
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 5,
                        title: 'Fifth entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 6,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 7,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 8,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 9,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 10,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 11,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 12,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 13,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 14,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 15,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 16,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 17,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 18,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 19,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 20,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 21,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 22,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 23,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 24,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 25,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 26,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 27,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 28,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 29,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 30,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 31,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 32,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 33,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 34,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 35,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 36,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 37,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 38,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 39,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 40,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #2 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 41,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 42,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 43,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 44,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 45,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'human',
                        user_id: 2,
                        text: 'Run #2 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 46,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 47,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 48,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'human',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 49,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 50,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 51,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 52,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 53,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 54,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 55,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 56,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 57,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 58,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 59,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 60,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 61,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 62,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 63,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 64,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 65,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 66,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 67,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 68,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 69,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 70,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 71,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 72,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 73,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 74,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 75,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 76,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 77,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 78,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 79,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 80,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 81,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 82,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 83,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 84,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 85,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 86,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 87,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 88,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 89,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 90,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 91,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 92,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 93,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 94,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 95,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 96,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 97,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 98,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 99,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 100,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 101,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 102,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 103,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 104,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 105,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 106,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 107,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 108,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 109,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 110,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 111,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 112,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 113,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 114,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 115,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 1,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 116,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 117,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 1,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 118,
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        parent_log_id: 117,
                        root_log_id: 117,
                        user_id: null,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        id: 119,
                        title: 'Another entry, with a title so long that it will probably be displayed with a balloon on it!',
                        subtype: 'comment',
                        origin: 'process',
                        parent_log_id: 117,
                        root_log_id: 117,
                        user_id: 1,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                ], { transaction }),
            ])),

    down: async (queryInterface) =>
        queryInterface.sequelize.transaction((transaction) =>
            Promise.all([queryInterface.bulkDelete('logs', null, { transaction })])),
};
