/**
 * @license
 * Copyright CERN and copyright holders of ALICE O2. This software is
 * distributed under the terms of the GNU General Public License v3 (GPL
 * Version 3), copied verbatim in the file "COPYING".
 *
 * See http://alice-o2.web.cern.ch/license for full licensing information.
 *
 * In applying this license CERN does not waive the privileges and immunities
 * granted to it by virtue of its status as an Intergovernmental Organization
 * or submit itself to any jurisdiction.
 */

module.exports = {
    up: async ({ context: { queryInterface } }) =>
        queryInterface.sequelize.transaction((transaction) =>
            Promise.all([
                queryInterface.bulkInsert('runs', [
                    {
                        id: 1,
                        run_number: 1,
                        time_o2_start: '2022-03-21 13:00:00',
                        time_o2_end: '2022-03-22 15:00:00',
                        time_trg_start: '2022-03-21 13:00:00',
                        time_trg_end: '2022-03-22 15:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 10,
                        n_epns: 10,
                        n_subtimeframes: 10,
                        bytes_read_out: 1024,
                        dd_flp: false,
                        dcs: true,
                        epn: true,
                        fill_number: 5,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        trigger_value: 'OFF',
                        run_type_id: 1,
                        lhc_period: 'lhc22b',
                        odc_topology_full_name: 'hash',
                        pdp_workflow_parameters: 'QC,GPU,CTF,EVENT_DISPLAY',
                        pdp_beam_type: 'cosmic',
                        readout_cfg_uri: 'Repository hash',
                    },
                    {
                        id: 2,
                        run_number: 2,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'bad',
                        n_detectors: 3,
                        n_flps: 10,
                        n_epns: 10,
                        n_subtimeframes: 10,
                        bytes_read_out: 1024,
                        dd_flp: false,
                        epn: false,
                        fill_number: 5,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        trigger_value: 'OFF',
                        run_type_id: 1,
                        lhc_period: 'lhc22b',
                        odc_topology_full_name: 'hash',
                    },
                    {
                        id: 3,
                        run_number: 3,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 3,
                        n_flps: 10,
                        n_epns: 10,
                        n_subtimeframes: 10,
                        bytes_read_out: 1024,
                        dd_flp: false,
                        dcs: false,
                        fill_number: 5,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        trigger_value: 'OFF',
                        run_type_id: 1,
                    },
                    {
                        id: 4,
                        run_number: 4,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 10,
                        n_epns: 10,
                        n_subtimeframes: 10,
                        bytes_read_out: 1024,
                        dd_flp: false,
                        dcs: false,
                        epn: true,
                        fill_number: 5,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        trigger_value: 'OFF',
                        run_type_id: 1,
                    },
                    {
                        id: 5,
                        run_number: 5,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 3,
                        n_flps: 10,
                        n_epns: 10,
                        n_subtimeframes: 10,
                        bytes_read_out: 1024,
                        dd_flp: false,
                        dcs: false,
                        epn: true,
                        fill_number: 5,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        trigger_value: 'OFF',
                        run_type_id: 1,
                    },
                    {
                        id: 6,
                        run_number: 6,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dcs: false,
                        epn: true,
                        fill_number: 5,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        trigger_value: 'LTU',
                        run_type_id: 2,
                    },

                    {
                        id: 7,
                        run_number: 7,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: false,
                        dcs: false,
                        epn: true,
                        fill_number: 5,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        trigger_value: 'LTU',
                        odc_topology_full_name: 'hash',
                        run_type_id: 3,
                    },
                    {
                        id: 8,
                        run_number: 8,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: false,
                        dcs: false,
                        epn: true,
                        fill_number: 5,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        trigger_value: 'LTU',
                        odc_topology_full_name: 'production/production.desc',
                    },
                    {
                        id: 9,
                        run_number: 9,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        fill_number: 5,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        trigger_value: 'CTP',
                        odc_topology_full_name: 'hash',
                    },
                    {
                        id: 10,
                        run_number: 10,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        trigger_value: 'CTP',
                        odc_topology_full_name: 'production/production.desc',
                    },
                    {
                        id: 11,
                        run_number: 11,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        trigger_value: 'CTP',
                        odc_topology_full_name: 'production/production.desc',
                        run_type_id: 4,
                    },
                    {
                        id: 12,
                        run_number: 12,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        trigger_value: 'CTP',
                        odc_topology_full_name: 'production/production.desc',
                    },
                    {
                        id: 13,
                        run_number: 13,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        trigger_value: 'CTP',
                    },
                    {
                        id: 14,
                        run_number: 14,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 15,
                        run_number: 15,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 16,
                        run_number: 16,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 17,
                        run_number: 17,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 18,
                        run_number: 18,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 19,
                        run_number: 19,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 20,
                        run_number: 20,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 21,
                        run_number: 21,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 22,
                        run_number: 22,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 23,
                        run_number: 23,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 24,
                        run_number: 24,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 25,
                        run_number: 25,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 26,
                        run_number: 26,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 27,
                        run_number: 27,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 28,
                        run_number: 28,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 29,
                        run_number: 29,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 30,
                        run_number: 30,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 31,
                        run_number: 31,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 32,
                        run_number: 32,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 33,
                        run_number: 33,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 34,
                        run_number: 34,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 35,
                        run_number: 35,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 36,
                        run_number: 36,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 37,
                        run_number: 37,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 38,
                        run_number: 38,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 39,
                        run_number: 39,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 40,
                        run_number: 40,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 41,
                        run_number: 41,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 42,
                        run_number: 42,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 43,
                        run_number: 43,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 44,
                        run_number: 44,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 45,
                        run_number: 45,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 46,
                        run_number: 46,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 47,
                        run_number: 47,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 48,
                        run_number: 48,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 49,
                        run_number: 49,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 2,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: true,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'ITS',
                        fill_number: 4,
                        trigger_value: 'CTP',
                        lhc_beam_energy: 23.21,
                        lhc_beta_star: 321.1321,
                        alice_l3_current: 30002545.12,
                        alice_dipole_current: 23.213215,
                        alice_dipole_polarity: 'NEGATIVE',
                        tfb_dd_mode: 'processing',
                        pdp_workflow_parameters: 'QC,GPU,CTF,EVENT_DISPLAY',
                    },
                    {
                        id: 50,
                        run_number: 50,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        fill_number: 1,
                        lhc_beam_energy: 23.21,
                        lhc_beam_mode: 'STABLE',
                        lhc_beta_star: 321.1321,
                        alice_l3_current: 30002545.12,
                        alice_l3_polarity: 'POSITIVE',
                        alice_dipole_current: 23.213215,
                    },
                    {
                        id: 51,
                        run_number: 51,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        fill_number: 2,
                        lhc_beam_energy: 23.21,
                        lhc_beam_mode: 'STABLE',
                        lhc_beta_star: 321.1321,
                        alice_l3_current: 30002545.12,
                        alice_l3_polarity: 'NEGATIVE',
                        alice_dipole_current: 23.213215,
                        alice_dipole_polarity: 'POSITIVE',
                    },
                    {
                        id: 52,
                        run_number: 52,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        fill_number: 3,
                        lhc_beam_energy: 23.21,
                        lhc_beam_mode: 'STABLE',
                        lhc_beta_star: 321.1321,
                        alice_l3_current: 30002545.12,
                        alice_l3_polarity: 'POSITIVE',
                        alice_dipole_current: 23.213215,
                        alice_dipole_polarity: 'NEGATIVE',
                    },
                    {
                        id: 53,
                        run_number: 53,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        fill_number: 4,
                        lhc_beam_energy: 23.21,
                        lhc_beam_mode: 'STABLE',
                        lhc_beta_star: 321.1321,
                        alice_l3_current: 30002545.12,
                        alice_l3_polarity: 'POSITIVE',
                        alice_dipole_current: 23.213215,
                        alice_dipole_polarity: 'NEGATIVE',
                    },
                    {
                        id: 54,
                        run_number: 54,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 17:00:00',
                        time_trg_start: '2019-08-08 14:00:00',
                        time_trg_end: '2019-08-08 16:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 2,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: true,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'ITS',
                        trigger_value: 'CTP',
                        fill_number: 6,
                        lhc_beam_energy: 23.21,
                        lhc_beam_mode: 'STABLE',
                        lhc_beta_star: 321.1321,
                        alice_l3_current: 30002545.12,
                        alice_dipole_current: 23.213215,
                        alice_dipole_polarity: 'NEGATIVE',
                        tfb_dd_mode: 'processing',
                        pdp_workflow_parameters: 'QC,GPU,CTF,EVENT_DISPLAY',
                    },
                    {
                        id: 55,
                        run_number: 55,
                        time_o2_start: '2019-08-08 14:00:00',
                        time_o2_end: '2019-08-08 19:00:00',
                        time_trg_start: '2019-08-08 16:00:00',
                        time_trg_end: '2019-08-08 18:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 1,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: true,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'FT0',
                        trigger_value: 'CTP',
                        fill_number: 6,
                        tfb_dd_mode: 'processing',
                        pdp_workflow_parameters: 'QC,GPU,CTF,EVENT_DISPLAY',
                    },
                    {
                        id: 56,
                        run_number: 56,
                        time_o2_start: '2019-08-08 19:00:00',
                        time_o2_end: '2019-08-08 22:00:00',
                        time_trg_start: '2019-08-08 20:00:00',
                        time_trg_end: '2019-08-08 21:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 2,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: true,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'ITS, FT0',
                        trigger_value: 'CTP',
                        fill_number: 6,
                        tfb_dd_mode: 'processing',
                        pdp_workflow_parameters: 'QC,GPU,CTF,EVENT_DISPLAY',
                    },
                    {
                        id: 57,
                        run_number: 57,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 2,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: true,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'ITS, CPV',
                        trigger_value: 'CTP',
                        tfb_dd_mode: 'processing',
                        pdp_workflow_parameters: 'QC,GPU,CTF,EVENT_DISPLAY',
                    },
                    {
                        id: 58,
                        run_number: 58,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 1,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: true,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        trigger_value: 'CTP',
                        fill_number: 6,
                        tfb_dd_mode: 'processing',
                        pdp_workflow_parameters: 'QC,GPU,CTF,EVENT_DISPLAY',
                    },
                    {
                        id: 59,
                        run_number: 59,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 1,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        pdp_beam_type: 'technical',
                    },
                    {
                        id: 60,
                        run_number: 60,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 1,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        trigger_value: 'OFF',
                        detectors: 'CPV',
                        readout_cfg_uri: 'file:///22-03-23/beam-pp/replay-data/chf',
                        pdp_workflow_parameters: 'QC,GPU,CTF,EVENT_DISPLAY',
                    },
                    {
                        id: 61,
                        run_number: 61,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 1,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        trigger_value: 'OFF',
                        detectors: 'CPV',
                        pdp_beam_type: 'technical',
                        readout_cfg_uri: 'file:///22-03-23/beam-pbpb/replay-data/chf',
                        pdp_workflow_parameters: 'QC,GPU,EVENT_DISPLAY',
                    },
                    {
                        id: 62,
                        run_number: 62,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 1,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        trigger_value: 'OFF',
                        detectors: 'CPV',
                        readout_cfg_uri: 'file:///22-03-23/beam-invalid/replay-data/chf',
                        pdp_workflow_parameters: 'QC,GPU,CTF,EVENT_DISPLAY',
                    },
                    {
                        id: 63,
                        run_number: 63,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 64,
                        run_number: 64,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 65,
                        run_number: 65,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 66,
                        run_number: 66,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 67,
                        run_number: 67,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 68,
                        run_number: 68,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 69,
                        run_number: 69,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 70,
                        run_number: 70,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 71,
                        run_number: 71,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 72,
                        run_number: 72,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 73,
                        run_number: 73,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 74,
                        run_number: 74,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 75,
                        run_number: 75,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 76,
                        run_number: 76,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 77,
                        run_number: 77,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 78,
                        run_number: 78,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 79,
                        run_number: 79,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 80,
                        run_number: 80,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 81,
                        run_number: 81,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 82,
                        run_number: 82,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 83,
                        run_number: 83,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 84,
                        run_number: 84,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 85,
                        run_number: 85,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 86,
                        run_number: 86,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        env_id: 'VODdsO12d',
                    },
                    {
                        id: 87,
                        run_number: 87,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        env_id: 'VODdsO12d',
                    },
                    {
                        id: 88,
                        run_number: 88,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        env_id: 'VODdsO12d',
                    },
                    {
                        id: 89,
                        run_number: 89,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        env_id: 'VODdsO12d',
                    },
                    {
                        id: 90,
                        run_number: 90,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        env_id: 'VODdsO12d',
                    },
                    {
                        id: 91,
                        run_number: 91,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        env_id: 'KGIS12DS',
                    },
                    {
                        id: 92,
                        run_number: 92,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        env_id: 'KGIS12DS',
                    },
                    {
                        id: 93,
                        run_number: 93,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'test',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        env_id: 'KGIS12DS',
                    },
                    {
                        id: 94,
                        run_number: 94,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        env_id: 'EIDO13i3D',
                    },
                    {
                        id: 95,
                        run_number: 95,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        env_id: 'EIDO13i3D',
                    },
                    {
                        id: 96,
                        run_number: 96,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        env_id: 'EIDO13i3D',
                    },
                    {
                        id: 97,
                        run_number: 97,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 98,
                        run_number: 98,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 99,
                        run_number: 99,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: '1234567890',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                    },
                    {
                        id: 100,
                        run_number: 100,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: 'ABCDEFGHIJ',
                        run_quality: 'test',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        env_id: 'Dxi029djX',
                    },
                    {
                        id: 101,
                        run_number: 101,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: 'ABCDEFGHIJ',
                        run_quality: 'good',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        env_id: 'Dxi029djX',
                    },
                    {
                        id: 102,
                        run_number: 102,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: 'ABCDEFGHIJ',
                        run_quality: 'good',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        env_id: 'Dxi029djX',
                    },
                    {
                        id: 103,
                        run_number: 103,
                        environment_id: 'ABCDEFGHIJ',
                        run_quality: 'good',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        env_id: 'TDI59So3d',
                        pdp_workflow_parameters: 'QC,GPU,CTF,EVENT_DISPLAY',
                        pdp_beam_type: 'cosmic',
                        readout_cfg_uri: 'Hash',
                    },
                    {
                        id: 104,
                        run_number: 104,
                        time_o2_end: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-08 13:00:00',
                        environment_id: 'ABCDEFGHIJ',
                        run_quality: 'good',
                        n_detectors: 6,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        env_id: 'TDI59So3d',
                        run_type_id: 1,
                        pdp_workflow_parameters: 'QC,GPU,CTF,EVENT_DISPLAY',
                        pdp_beam_type: 'cosmic',
                        readout_cfg_uri: 'Repository hash',
                    },
                    {
                        id: 105,
                        run_number: 105,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        environment_id: '0987654321',
                        run_quality: 'test',
                        n_detectors: 3,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        fill_number: 1,
                        epn_topology: 'normal',
                        detectors: 'CPV',
                        env_id: 'TDI59So3d',
                        lhc_period: 'lhc22a',
                        run_type_id: 1,
                        pdp_workflow_parameters: 'QC,CTF,EVENT_DISPLAY',
                        pdp_beam_type: 'cosmic',
                        readout_cfg_uri: 'Repository hash',
                    },
                    {
                        id: 106,
                        run_number: 106,
                        time_o2_start: '2019-08-08 13:00:00',
                        time_o2_end: '2019-08-09 14:00:00',
                        time_trg_start: '2019-08-08 13:00:00',
                        time_trg_end: '2019-08-09 14:00:00',
                        environment_id: '0987654321',
                        run_quality: 'good',
                        n_detectors: 15,
                        n_flps: 12,
                        n_epns: 12,
                        n_subtimeframes: 12,
                        bytes_read_out: 64,
                        dd_flp: true,
                        dcs: false,
                        epn: true,
                        fill_number: 1,
                        epn_topology: 'a quite long topology, which will for sure require a balloon to be displayed properly',
                        detectors: 'ACO, CPV, CTP, EMC, FIT, HMP, ITS, MCH, MFT, MID, PHS, TOF, TPC, TRD, ZDC',
                        lhc_period: 'lhc22b',
                        odc_topology_full_name: 'hash',
                        run_type_id: 1,
                        pdp_workflow_parameters: 'QC,GPU,CTF,EVENT_DISPLAY',
                        pdp_beam_type: 'cosmic',
                        readout_cfg_uri: 'Repository hash',
                    },
                ], { transaction }),
            ])),

    down: async ({ context: { queryInterface } }) =>
        queryInterface.sequelize.transaction((transaction) =>
            Promise.all([queryInterface.bulkDelete('runs', null, { transaction })])),
};
