/**
 * @license
 * Copyright CERN and copyright holders of ALICE O2. This software is
 * distributed under the terms of the GNU General Public License v3 (GPL
 * Version 3), copied verbatim in the file "COPYING".
 *
 * See http://alice-o2.web.cern.ch/license for full licensing information.
 *
 * In applying this license CERN does not waive the privileges and immunities
 * granted to it by virtue of its status as an Intergovernmental Organization
 * or submit itself to any jurisdiction.
 */

module.exports = {
    up: async (queryInterface) =>
        queryInterface.sequelize.transaction((transaction) =>
            Promise.all([
                queryInterface.bulkInsert('logs', [
                    {
                        title: 'First entry',
                        subtype: 'run',
                        origin: 'human',
                        user_id: 1,
                        text: 'Power interruption due to unplugged wire.',
                        created_at: new Date('2000-01-02 12:00:00 PM'),
                    },
                    {
                        title: 'Second entry',
                        subtype: 'subsystem',
                        origin: 'process',
                        user_id: 1,
                        text: 'Detected particle ABC123',
                        parent_log_id: 1,
                        root_log_id: 1,
                        created_at: new Date('2020-02-02 12:00:00 PM'),
                    },
                    {
                        title: 'Third entry',
                        subtype: 'announcement',
                        origin: 'human',
                        text: 'Cake at the particle accelerator!',
                        parent_log_id: 1,
                        root_log_id: 1,
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Fourth entry',
                        subtype: 'comment',
                        origin: 'human',
                        user_id: 2,
                        text: 'The cake is a lie!',
                        parent_log_id: 2,
                        root_log_id: 1,
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Fifth entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #2 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'human',
                        user_id: 2,
                        text: 'Run #2 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'human',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 1,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        user_id: 1,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry',
                        subtype: 'run',
                        origin: 'process',
                        root_log_id: 117,
                        user_id: 2,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                    {
                        title: 'Another entry, with a title so long that it will probably be displayed with a balloon on it!',
                        subtype: 'subsystem',
                        origin: 'process',
                        root_log_id: 117,
                        user_id: 1,
                        text: 'Run #1 stopped',
                        created_at: new Date('2019-11-11 12:00:00 PM'),
                    },
                ], { transaction }),
            ])),

    down: async (queryInterface) =>
        queryInterface.sequelize.transaction((transaction) =>
            Promise.all([queryInterface.bulkDelete('logs', null, { transaction })])),
};
