/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.0.0-beta2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ArrayOfRunsResponse.h
 *
 * Response containing multiple runs.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ArrayOfRunsResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ArrayOfRunsResponse_H_


#include "../ModelBase.h"

#include "ArrayOfRunsResponseMeta.h"
#include "Run.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// Response containing multiple runs.
/// </summary>
class  ArrayOfRunsResponse
    : public ModelBase
{
public:
    ArrayOfRunsResponse();
    virtual ~ArrayOfRunsResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// ArrayOfRunsResponse members

    /// <summary>
    /// A list of Run objects.
    /// </summary>
    std::vector<std::shared_ptr<Run>>& getData();
    bool dataIsSet() const;
    void unsetData();

    void setData(const std::vector<std::shared_ptr<Run>>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<ArrayOfRunsResponseMeta> getMeta() const;
    bool metaIsSet() const;
    void unsetMeta();

    void setMeta(const std::shared_ptr<ArrayOfRunsResponseMeta>& value);


protected:
    std::vector<std::shared_ptr<Run>> m_Data;
    bool m_DataIsSet;
    std::shared_ptr<ArrayOfRunsResponseMeta> m_Meta;
    bool m_MetaIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ArrayOfRunsResponse_H_ */
