/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.4.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ArrayOfSubsystemsResponse.h
 *
 * Response containing multiple subsystems.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ArrayOfSubsystemsResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ArrayOfSubsystemsResponse_H_


#include "ModelBase.h"

#include "model/Subsystem.h"
#include "model/ArrayOfSubsystemsResponseMeta.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// Response containing multiple subsystems.
/// </summary>
class  ArrayOfSubsystemsResponse
    : public ModelBase
{
public:
    ArrayOfSubsystemsResponse();
    virtual ~ArrayOfSubsystemsResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// ArrayOfSubsystemsResponse members

    /// <summary>
    /// A list of Subsystem objects.
    /// </summary>
    std::vector<std::shared_ptr<Subsystem>>& getData();
    bool dataIsSet() const;
    void unsetData();

    void setData(const std::vector<std::shared_ptr<Subsystem>>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<ArrayOfSubsystemsResponseMeta> getMeta() const;
    bool metaIsSet() const;
    void unsetMeta();

    void setMeta(const std::shared_ptr<ArrayOfSubsystemsResponseMeta>& value);


protected:
    std::vector<std::shared_ptr<Subsystem>> m_Data;
    bool m_DataIsSet;
    std::shared_ptr<ArrayOfSubsystemsResponseMeta> m_Meta;
    bool m_MetaIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ArrayOfSubsystemsResponse_H_ */
