/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.0.0-beta2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ArrayOfFlpsResponse.h
 *
 * Response containing multiple flps.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ArrayOfFlpsResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ArrayOfFlpsResponse_H_


#include "../ModelBase.h"

#include "Flp.h"
#include "ArrayOfFlpsResponseMeta.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// Response containing multiple flps.
/// </summary>
class  ArrayOfFlpsResponse
    : public ModelBase
{
public:
    ArrayOfFlpsResponse();
    virtual ~ArrayOfFlpsResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// ArrayOfFlpsResponse members

    /// <summary>
    /// A list of Flp objects.
    /// </summary>
    std::vector<std::shared_ptr<Flp>>& getData();
    bool dataIsSet() const;
    void unsetData();

    void setData(const std::vector<std::shared_ptr<Flp>>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<ArrayOfFlpsResponseMeta> getMeta() const;
    bool metaIsSet() const;
    void unsetMeta();

    void setMeta(const std::shared_ptr<ArrayOfFlpsResponseMeta>& value);


protected:
    std::vector<std::shared_ptr<Flp>> m_Data;
    bool m_DataIsSet;
    std::shared_ptr<ArrayOfFlpsResponseMeta> m_Meta;
    bool m_MetaIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ArrayOfFlpsResponse_H_ */
