/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.0.0-beta2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ArrayOfFlpsResponseMeta.h
 *
 * The metadata related to an array of flps response.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ArrayOfFlpsResponseMeta_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ArrayOfFlpsResponseMeta_H_


#include "../ModelBase.h"

#include "PaginationMeta.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// The metadata related to an array of flps response.
/// </summary>
class  ArrayOfFlpsResponseMeta
    : public ModelBase
{
public:
    ArrayOfFlpsResponseMeta();
    virtual ~ArrayOfFlpsResponseMeta();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// ArrayOfFlpsResponseMeta members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<PaginationMeta> getPage() const;
    bool pageIsSet() const;
    void unsetPage();

    void setPage(const std::shared_ptr<PaginationMeta>& value);


protected:
    std::shared_ptr<PaginationMeta> m_Page;
    bool m_PageIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ArrayOfFlpsResponseMeta_H_ */
