/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.0.0-beta2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * FilterLogsCreatedOptions.h
 *
 * Specifies the creation time related filter requirements for a request.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_FilterLogsCreatedOptions_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_FilterLogsCreatedOptions_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// Specifies the creation time related filter requirements for a request.
/// </summary>
class  FilterLogsCreatedOptions
    : public ModelBase
{
public:
    FilterLogsCreatedOptions();
    virtual ~FilterLogsCreatedOptions();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// FilterLogsCreatedOptions members

    /// <summary>
    /// The earliest allowed unix timestamp for the fetched data.
    /// </summary>
    utility::datetime getFrom() const;
    bool fromIsSet() const;
    void unsetFrom();

    void setFrom(const utility::datetime& value);

    /// <summary>
    /// The latest allowed unix timestamp for the fetched data.
    /// </summary>
    utility::datetime getTo() const;
    bool toIsSet() const;
    void unsetTo();

    void setTo(const utility::datetime& value);


protected:
    utility::datetime m_From;
    bool m_FromIsSet;
    utility::datetime m_To;
    bool m_ToIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_FilterLogsCreatedOptions_H_ */
