/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.0.0-beta2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * FilterLogsOptions.h
 *
 * Specifies the log related filter requirements for a request.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_FilterLogsOptions_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_FilterLogsOptions_H_


#include "../ModelBase.h"

#include "FilterLogsTagOptions.h"
#include "FilterLogsCreatedOptions.h"
#include <cpprest/details/basic_types.h>
#include "LogOrigin.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// Specifies the log related filter requirements for a request.
/// </summary>
class  FilterLogsOptions
    : public ModelBase
{
public:
    FilterLogsOptions();
    virtual ~FilterLogsOptions();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// FilterLogsOptions members

    /// <summary>
    /// Name of the author.
    /// </summary>
    utility::string_t getAuthor() const;
    bool authorIsSet() const;
    void unsetAuthor();

    void setAuthor(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<FilterLogsCreatedOptions> getCreated() const;
    bool createdIsSet() const;
    void unsetCreated();

    void setCreated(const std::shared_ptr<FilterLogsCreatedOptions>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<LogOrigin> getOrigin() const;
    bool originIsSet() const;
    void unsetOrigin();

    void setOrigin(const std::shared_ptr<LogOrigin>& value);

    /// <summary>
    /// The unique identifier of this entity.
    /// </summary>
    int32_t getParentLog() const;
    bool parentLogIsSet() const;
    void unsetParentLog();

    void setParentLog(int32_t value);

    /// <summary>
    /// The unique identifier of this entity.
    /// </summary>
    int32_t getRootLog() const;
    bool rootLogIsSet() const;
    void unsetRootLog();

    void setRootLog(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<FilterLogsTagOptions> getTag() const;
    bool tagIsSet() const;
    void unsetTag();

    void setTag(const std::shared_ptr<FilterLogsTagOptions>& value);

    /// <summary>
    /// Title of the log.
    /// </summary>
    utility::string_t getTitle() const;
    bool titleIsSet() const;
    void unsetTitle();

    void setTitle(const utility::string_t& value);


protected:
    utility::string_t m_Author;
    bool m_AuthorIsSet;
    std::shared_ptr<FilterLogsCreatedOptions> m_Created;
    bool m_CreatedIsSet;
    std::shared_ptr<LogOrigin> m_Origin;
    bool m_OriginIsSet;
    int32_t m_ParentLog;
    bool m_ParentLogIsSet;
    int32_t m_RootLog;
    bool m_RootLogIsSet;
    std::shared_ptr<FilterLogsTagOptions> m_Tag;
    bool m_TagIsSet;
    utility::string_t m_Title;
    bool m_TitleIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_FilterLogsOptions_H_ */
