/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.0.0-beta2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Log_runs.h
 *
 * Minified Run object.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Log_runs_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Log_runs_H_


#include "../ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// Minified Run object.
/// </summary>
class  Log_runs
    : public ModelBase
{
public:
    Log_runs();
    virtual ~Log_runs();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Log_runs members

    /// <summary>
    /// The unique identifier of this entity.
    /// </summary>
    int32_t getId() const;
    bool idIsSet() const;
    void unsetId();

    void setId(int32_t value);

    /// <summary>
    /// The unique identifier of this entity.
    /// </summary>
    int64_t getRunNumber() const;
    bool runNumberIsSet() const;
    void unsetRunNumber();

    void setRunNumber(int64_t value);


protected:
    int32_t m_Id;
    bool m_IdIsSet;
    int64_t m_RunNumber;
    bool m_RunNumberIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Log_runs_H_ */
