/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.4.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "LogOrigin.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



namespace
{
using EnumUnderlyingType = utility::string_t;

LogOrigin::eLogOrigin toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(U("human")))
        return LogOrigin::eLogOrigin::LogOrigin_HUMAN;
    if (val == utility::conversions::to_string_t(U("process")))
        return LogOrigin::eLogOrigin::LogOrigin_PROCESS;
    return {};
}

EnumUnderlyingType fromEnum(LogOrigin::eLogOrigin e)
{
    switch (e)
    {
    case LogOrigin::eLogOrigin::LogOrigin_HUMAN:
        return U("human");
    case LogOrigin::eLogOrigin::LogOrigin_PROCESS:
        return U("process");
    default:
        break;
    }
    return {};
}
}

LogOrigin::LogOrigin()
{
}

LogOrigin::~LogOrigin()
{
}

void LogOrigin::validate()
{
    // TODO: implement validation
}

web::json::value LogOrigin::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool LogOrigin::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void LogOrigin::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool LogOrigin::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

LogOrigin::eLogOrigin LogOrigin::getValue() const
{
   return m_value;
}

void LogOrigin::setValue(LogOrigin::eLogOrigin const value)
{
   m_value = value;
}


}
}
}
}


