/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.0.0-beta2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "LogOrigin.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



LogOrigin::LogOrigin()
{
}

LogOrigin::~LogOrigin()
{
}

void LogOrigin::validate()
{
    // TODO: implement validation
}

web::json::value LogOrigin::toJson() const
{
    web::json::value val = web::json::value::object();

    
    if (m_value == eLogOrigin::LogOrigin_HUMAN) val = web::json::value::string(U("human"));
    if (m_value == eLogOrigin::LogOrigin_PROCESS) val = web::json::value::string(U("process"));

    return val;
}

bool LogOrigin::fromJson(const web::json::value& val)
{
    auto s = val.as_string();

    
    if (s == utility::conversions::to_string_t("human")) m_value = eLogOrigin::LogOrigin_HUMAN;
    if (s == utility::conversions::to_string_t("process")) m_value = eLogOrigin::LogOrigin_PROCESS;
    return true;
}

void LogOrigin::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    utility::string_t s;

    
    if (m_value == eLogOrigin::LogOrigin_HUMAN) s = utility::conversions::to_string_t("human");
    if (m_value == eLogOrigin::LogOrigin_PROCESS) s = utility::conversions::to_string_t("process");

    multipart->add(ModelBase::toHttpContent(namePrefix, s));
}

bool LogOrigin::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }
    {
        utility::string_t s;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), s);
        eLogOrigin v;

        
        if (s == utility::conversions::to_string_t("human")) v = eLogOrigin::LogOrigin_HUMAN;
        if (s == utility::conversions::to_string_t("process")) v = eLogOrigin::LogOrigin_PROCESS;

        setValue(v);
    }
    return ok;
}

LogOrigin::eLogOrigin LogOrigin::getValue() const
{
   return m_value;
}

void LogOrigin::setValue(LogOrigin::eLogOrigin const value)
{
   m_value = value;
}


}
}
}
}


