/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.0.0-beta2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PaginationOptions.h
 *
 * Specifies the pagination requirements of a request.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_PaginationOptions_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_PaginationOptions_H_


#include "../ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// Specifies the pagination requirements of a request.
/// </summary>
class  PaginationOptions
    : public ModelBase
{
public:
    PaginationOptions();
    virtual ~PaginationOptions();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// PaginationOptions members

    /// <summary>
    /// The numbers of items to return.
    /// </summary>
    int32_t getLimit() const;
    bool limitIsSet() const;
    void unsetLimit();

    void setLimit(int32_t value);

    /// <summary>
    /// The number of items to skip before starting to collect the result set.
    /// </summary>
    int32_t getOffset() const;
    bool offsetIsSet() const;
    void unsetOffset();

    void setOffset(int32_t value);


protected:
    int32_t m_Limit;
    bool m_LimitIsSet;
    int32_t m_Offset;
    bool m_OffsetIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_PaginationOptions_H_ */
