/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.0.0-beta2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PaginationMeta.h
 *
 * The metadata related to pagination.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_PaginationMeta_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_PaginationMeta_H_


#include "../ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// The metadata related to pagination.
/// </summary>
class  PaginationMeta
    : public ModelBase
{
public:
    PaginationMeta();
    virtual ~PaginationMeta();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// PaginationMeta members

    /// <summary>
    /// The total number of pages which contain data.
    /// </summary>
    int32_t getPageCount() const;
    bool pageCountIsSet() const;
    void unsetPageCount();

    void setPageCount(int32_t value);

    /// <summary>
    /// The total number of elements in the collection
    /// </summary>
    int32_t getTotalCount() const;
    bool totalCountIsSet() const;
    void unsetTotalCount();

    void setTotalCount(int32_t value);


protected:
    int32_t m_PageCount;
    bool m_PageCountIsSet;
    int32_t m_TotalCount;
    bool m_TotalCountIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_PaginationMeta_H_ */
