/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.0.0-beta2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * RunSortOptions.h
 *
 * Specifies the sorting requirements of a run request.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_RunSortOptions_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_RunSortOptions_H_


#include "../ModelBase.h"

#include "SortOrder.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// Specifies the sorting requirements of a run request.
/// </summary>
class  RunSortOptions
    : public ModelBase
{
public:
    RunSortOptions();
    virtual ~RunSortOptions();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// RunSortOptions members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<SortOrder> getId() const;
    bool idIsSet() const;
    void unsetId();

    void setId(const std::shared_ptr<SortOrder>& value);


protected:
    std::shared_ptr<SortOrder> m_Id;
    bool m_IdIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_RunSortOptions_H_ */
