/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.4.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "RunType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



namespace
{
using EnumUnderlyingType = utility::string_t;

RunType::eRunType toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(U("physics")))
        return RunType::eRunType::RunType_PHYSICS;
    if (val == utility::conversions::to_string_t(U("cosmics")))
        return RunType::eRunType::RunType_COSMICS;
    if (val == utility::conversions::to_string_t(U("technical")))
        return RunType::eRunType::RunType_TECHNICAL;
    return {};
}

EnumUnderlyingType fromEnum(RunType::eRunType e)
{
    switch (e)
    {
    case RunType::eRunType::RunType_PHYSICS:
        return U("physics");
    case RunType::eRunType::RunType_COSMICS:
        return U("cosmics");
    case RunType::eRunType::RunType_TECHNICAL:
        return U("technical");
    default:
        break;
    }
    return {};
}
}

RunType::RunType()
{
}

RunType::~RunType()
{
}

void RunType::validate()
{
    // TODO: implement validation
}

web::json::value RunType::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool RunType::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void RunType::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool RunType::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

RunType::eRunType RunType::getValue() const
{
   return m_value;
}

void RunType::setValue(RunType::eRunType const value)
{
   m_value = value;
}


}
}
}
}


