/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.4.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SortOrder.h
 *
 * Specifies the sorting direction of a sorting option.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_SortOrder_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_SortOrder_H_


#include "ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {

class  SortOrder
    : public ModelBase
{
public:
    SortOrder();
    virtual ~SortOrder();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eSortOrder
    {
        SortOrder_ASC,
        SortOrder_DESC,
    };

    eSortOrder getValue() const;
    void setValue(eSortOrder const value);

    protected:
        eSortOrder m_value;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_SortOrder_H_ */
