/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.4.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "StatusDataResponse.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {




StatusDataResponse::StatusDataResponse()
{
    m_Host = utility::conversions::to_string_t("");
    m_HostIsSet = false;
    m_Port = 0.0;
    m_PortIsSet = false;
}

StatusDataResponse::~StatusDataResponse()
{
}

void StatusDataResponse::validate()
{
    // TODO: implement validation
}

web::json::value StatusDataResponse::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_HostIsSet)
    {
        val[utility::conversions::to_string_t(U("host"))] = ModelBase::toJson(m_Host);
    }
    if(m_PortIsSet)
    {
        val[utility::conversions::to_string_t(U("port"))] = ModelBase::toJson(m_Port);
    }

    return val;
}

bool StatusDataResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("host"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("host")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_host;
            ok &= ModelBase::fromJson(fieldValue, refVal_host);
            setHost(refVal_host);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("port"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("port")));
        if(!fieldValue.is_null())
        {
            double refVal_port;
            ok &= ModelBase::fromJson(fieldValue, refVal_port);
            setPort(refVal_port);
        }
    }
    return ok;
}

void StatusDataResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_HostIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("host")), m_Host));
    }
    if(m_PortIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("port")), m_Port));
    }
}

bool StatusDataResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("host"))))
    {
        utility::string_t refVal_host;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("host"))), refVal_host );
        setHost(refVal_host);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("port"))))
    {
        double refVal_port;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("port"))), refVal_port );
        setPort(refVal_port);
    }
    return ok;
}

utility::string_t StatusDataResponse::getHost() const
{
    return m_Host;
}

void StatusDataResponse::setHost(const utility::string_t& value)
{
    m_Host = value;
    m_HostIsSet = true;
}

bool StatusDataResponse::hostIsSet() const
{
    return m_HostIsSet;
}

void StatusDataResponse::unsetHost()
{
    m_HostIsSet = false;
}
double StatusDataResponse::getPort() const
{
    return m_Port;
}

void StatusDataResponse::setPort(double value)
{
    m_Port = value;
    m_PortIsSet = true;
}

bool StatusDataResponse::portIsSet() const
{
    return m_PortIsSet;
}

void StatusDataResponse::unsetPort()
{
    m_PortIsSet = false;
}
}
}
}
}


