/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.4.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * StatusDataResponse.h
 *
 * GUI or DB status
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_StatusDataResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_StatusDataResponse_H_


#include "ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// GUI or DB status
/// </summary>
class  StatusDataResponse
    : public ModelBase
{
public:
    StatusDataResponse();
    virtual ~StatusDataResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// StatusDataResponse members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getHost() const;
    bool hostIsSet() const;
    void unsetHost();

    void setHost(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    double getPort() const;
    bool portIsSet() const;
    void unsetPort();

    void setPort(double value);


protected:
    utility::string_t m_Host;
    bool m_HostIsSet;
    double m_Port;
    bool m_PortIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_StatusDataResponse_H_ */
