name: Bookkeeping

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04]
        node-version: ['12.16.1']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing dependencies
        run: npm ci
      - name: Executing test suite
        run: npm test
        env:
          CI: true

  coverage:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04]
        node-version: ['12.16.1']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing dependencies
        run: npm ci
      - name: Executing test suite with coverage
        run: npm run coverage
        env:
          CI: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

  linter:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.16.1
        uses: actions/setup-node@v1
        with:
          node-version: '12.16.1'
      - name: Installing dependencies
        run: npm ci
      - name: Running linter
        run: npm run lint
